# Generated by Django 2.1.5 on 2019-02-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
