# Generated by Django 2.1.5 on 2019-02-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login1', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
