# Generated by Django 2.1.5 on 2019-02-06 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandparticipate',
            old_name='band_id',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='bandparticipate',
            old_name='permission',
            new_name='is_band_leader',
        ),
        migrations.RenameField(
            model_name='bandparticipate',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(through='sig.BandParticipate', to=settings.AUTH_USER_MODEL),
        ),
    ]
