# Generated by Django 2.1.4 on 2019-02-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0003_auto_20190210_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandInvitationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=45, unique=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sig.Band')),
            ],
        ),
    ]
