# Generated by Django 2.1.4 on 2019-02-21 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sig', '0004_bandinvitationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandparticipate',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sig.Band'),
        ),
        migrations.AlterField(
            model_name='bandparticipate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bandparticipate',
            unique_together={('band', 'user')},
        ),
    ]
