# Generated by Django 2.1.4 on 2019-02-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0005_auto_20190221_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='band_leader',
        ),
        migrations.AddField(
            model_name='band',
            name='band_cover_img_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
