# Generated by Django 2.1.4 on 2019-02-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
    ]
