# Generated by Django 2.1.4 on 2019-02-23 14:42

from django.db import migrations, models
import file_manage.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='photo_height',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='photo_width',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='photo',
            field=models.ImageField(height_field='photo_height', upload_to=file_manage.models.user_directory_path, width_field='photo_width'),
        ),
    ]
