# Generated by Django 2.1.4 on 2019-02-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0002_auto_20190223_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='photo_height',
            field=models.PositiveIntegerField(default=100, editable=False),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='photo_width',
            field=models.PositiveIntegerField(default=100, editable=False),
        ),
    ]
